#!/bin/sh
set -eu

echo "=============================================="
echo " LibreChat Code Interpreter - Fly.io worker"
echo "=============================================="

cd /app/code-interpreter

if [ -z "${LIBRECHAT_CODE_SANDBOX_ENDPOINT:-}" ]; then
  echo ""
  echo "ERROR: LIBRECHAT_CODE_SANDBOX_ENDPOINT is missing."
  echo ""
  echo "This image is a REMOTE CODE BRIDGE worker."
  echo "It is not the Code Interpreter API/sandbox itself."
  echo ""
  echo "Create/pair the worker from:"
  echo "LibreChat -> Settings -> Code environments -> Connect VM"
  echo ""
  exit 1
fi

echo "Sandbox endpoint configured."
echo "Endpoint: ${LIBRECHAT_CODE_SANDBOX_ENDPOINT}"

# The remote bridge CLI is release-dependent. Prefer an installed CLI,
# otherwise expose the repository's available scripts instead of guessing.
if command -v librechat-code >/dev/null 2>&1; then
  exec librechat-code
fi

if [ -f package.json ]; then
  echo ""
  echo "Available package scripts:"
  npm run 2>/dev/null || true
fi

echo ""
echo "ERROR: librechat-code CLI is not installed in this checkout."
echo "Use the pairing command generated by LibreChat and install/start"
echo "the matching official @librechat/code worker release."
exit 1
