app = "librechat-code-fly"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2

[[mounts]]
  source = "code_data"
  destination = "/mnt/data"
  initial_size = "10gb"
